server:
  port: 8001

# 最佳实践：spring cloud应用都要指定application.name
spring:
  application:
    name: eureka-server

# 在默认情况下eureka server也是一个eureka client ,必须要指定一个 server
eureka:
  instance:
    hostname: localhost
  client:
    # 表明自己是一个eureka server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
