server:
  port: 8006

# 最佳实践：spring cloud应用都要指定application.name
spring:
  application:
    name: eureka-service-consumer-feign

# 在默认情况下eureka server也是一个eureka client ,必须要指定一个 server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

# 启用hystrix
feign:
  hystrix:
    enabled: true
