server:
#  port: 8002
  port: 8003

# 最佳实践：spring cloud应用都要指定application.name
spring:
  application:
    name: eureka-service-provider

# 在默认情况下eureka server也是一个eureka client ,必须要指定一个 server
eureka:
  instance:
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 5   # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 10 # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
