server:
  port: 8009

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # git仓库的地址
          uri: https://github.com/heylee-Y/spring-cloud-greenwich-demo.git
          # 配置仓库路径，这里是文件夹搜索路径
          search-paths: spring-cloud-config
          default-label: master

eureka:
  client:
    service-url:
      # 指定服务注册中心的地址
      defaultZone: http://localhost:8001/eureka/

  # 心跳检测检测与续约时间
  # 【测试】时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    lease-renewal-interval-in-seconds: 1   # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 2 #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。